### ISSUE TITLE
Chage in serialization output with trailing newline in `License` field

### ISSUE THREAD

**Issue by dnicolodi** [pypa/pyproject-metadata#202] opened 2024-10-11 08:57 UTC
In a project using
```toml
[project]
license = { file = 'LICENSE' }
```
with the content of `LICENSE` being
```
some license
```
including the trailing newline, with pyproject-metadata 0.8 I obtain a RFC822 serialization of the metadata that looks like:
```
License: some license\n
```
with pyproject-metadata 0.9.0b7 I obtain:
```
License: some license\n
         \n
```
where I made the newlines explicit in the RFC822 serialization. When the metadata is read back by `packaging.metadata.parse_email()` the latter results in a `license` field having content `some license\n         `. We can argue that whitespace at the end of the text field is not significant, but maybe we should keep stripping the trailing newline.

**Comment by dnicolodi** [comment] 2024-10-11 09:00
Also, would it maybe be better to reduce the indentation of subsequent lines in multi-line fields to just one or two spaces? It would made for an easier to read serialization format. And `packging.metadata.Metadata()` and friends do not strip leading white space from continuation lines, thus having less indentation would make the values obtained from them slightly less awkwards to  look at.

**Comment by henryiii** [comment] 2024-10-11 15:03
If the license file had a trailing newline, having it in the metadata seems correct. You have to have the trailing whitespace in order to preserve the newline. The email format doesn't actually support newlines - a new line followed by at least one white space is supposed to be merged into one space. The fact tools are keeping them is a bit of a hack.

As for the indentation, I followed setuptools, which indents based on the width of the header key. That would look a little odd coming out of `packging.metadata.Metadata`. I've also seen 7 spaces, due to the old body mechanism, which was seven white spaces followed by a `|` in order to preserve newlines.

**Comment by henryiii** [comment] 2024-10-12 03:46
I think I didn't account for  this part of PEP 639:

> If the specified license file is present in the source tree, build tools SHOULD use it to fill the License-File field in the core metadata, and MUST include the specified file as if it were specified in a license-file field. If the file does not exist at the specified path, tools MUST raise an informative error as previously specified.

**Comment by dnicolodi** [comment] 2024-10-12 08:53
Which part is not handled exactly? When `project.license` in `pyproject.toml` is a string, there should be no `License` field in the metadata emitted, just `License-Expression`. Any file matched by the globs in `project.license-files` goes into `License-File` fields. I think all this is covered. It is responsibility of the build backend to add the license files into the wheel.

**Comment by dnicolodi** [comment] 2024-10-12 14:23
The trailing newline thing is only annoying having to verify the metadata emitted by different versions of pyproject-metadata. But it is not hard to accommodate for the output of different versions. I just wanted to mention it.

Given that (hopefully) multi-line values in metadata fields are going away, I think the exact formatting of the continuation lines is not that important. However, I would like to use a bit less spaces.

**Comment by henryiii** [comment] 2024-10-13 02:01
> Which part is not handled exactly?

If a user has:

```toml
[project]
name = "example"
version = "0.1.0"
license.file = "LICENSE.txt"
```

then Metadata 2.4-supporting backends are supposed to show a warning and fill `Licence-File: LICENSE.txt`. But it doesn't say if `License:` should be filled with the contents or left blank.

**Comment by dnicolodi** [comment] 2024-10-13 08:02
`License` cannot exist in metadata version 2.4 and `License-File` is metadata version 2.4 only. Thus I think `Licnese` cannot be filled if `License-File` is emitted with metadata version 2.4. 

However, I don't like this feature of the PEP at all. It means that packages get updated to metadata 2.4 only for being built with a different version of the build backend. I think that what is implemented now in pyproject-metadata is much more sensible.

Another thing I don't like in the PEP is that IIUC `project.license-files` can be used without `project.license`. In this case, it is not clear to me how an user can easily identify the license, other than comparing the content of the license file with a database of license texts.

**Comment by henryiii** [comment] 2024-10-14 21:27
> It means that packages get updated to metadata 2.4

The PEP doesn't control whether a package decides to use 2.4 or not. AFAICT pyproject-metadata's implementation is a valid application of PEP 639, even if it's not suggested or recommended (or mentioned...).

> Another thing I don't like in the PEP is that IIUC project.license-files can be used without project.license. In this case, it is not clear to me how a user can easily identify the license, other than comparing the content of the license file with a database of license texts.

Ah, yes, don't think I noticed that. Not that it's any worse than the current situation, which is a "could mean anything" License field, optional classifiers (which are the only canonical place for license information), and files stuck anywhere in the `.dist-info` folder. :)

**Comment by henryiii** [comment] 2024-10-14 21:28
> License cannot exist in metadata version 2.4

Ah, if that's the case, that's the answer I was looking for. :)

**Comment by henryiii** [comment] 2024-10-14 21:35
Though is it?

> The legacy unstructured-text License [Core Metadata field](https://packaging.python.org/en/latest/glossary/#term-Core-Metadata-Field) is deprecated and replaced by the new License-Expression field. The fields are mutually exclusive. Tools which generate Core Metadata MUST NOT create both these fields. Tools which read Core Metadata, when dealing with both these fields present at the same time, MUST read the value of License-Expression and MUST disregard the value of the License field.

That says License and License-Expression are mutually exclusive. And that License is deprecated. It doesn't say License and License-File are, though. And because this is talking about METADATA 2.4, and it describes what should happen (warning on License being set to a SPDX expression), that sort of indicates you _can_ have License in METADATA 2.4.

**Comment by henryiii** [comment] 2024-10-14 21:37
(Unless I hear otherwise, though, I'm okay with not including it - the only way to hit this in pyproject-metadata is if a backend explicitly sets the metadata to 2.4)

**Comment by dnicolodi** [comment] 2024-10-14 21:46
> > It means that packages get updated to metadata 2.4
> 
> The PEP doesn't control whether a package decides to use 2.4 or not. AFAICT pyproject-metadata's implementation is a valid application of PEP 639, even if it's not suggested or recommended (or mentioned...).

What I meant is that a package using meson-python now that uses this license declaration
```toml
[prject]
license.file = 'LICENSE'
```
with pyproject-metadata 0.8 gets metadata version 2.1. However, if the letter of the PEP is implemented, because of the `License-File` filed that needs to be included, it would get metadata 2.4, which currently cannot be uploaded to PyPI. This would be quite a regression for which no obvious solution exists: new meson-python releases could force-set the metadata version, or depend on pyproject-metadata =~ 0.8, till PyPI accepts metadata 2.4, but there is not way to retroactively apply these fixes to existing meson-python releases.

**Comment by dnicolodi** [comment] 2024-10-14 21:49
> Not that it's any worse than the current situation, which is a "could mean anything" License field, optional classifiers (which are the only canonical place for license information), and files stuck anywhere in the `.dist-info` folder. :)

Sure, PEP 639 is better than the current mess, but I had hope for a bit more care in defining the new standard. This lack of attention to detail is the reason why the metadata format is such a mess.

**Comment by henryiii** [comment] 2024-10-14 21:53
owever, if the letter of the PEP is implemented,

I took it to mean that the PEP only discusses metadata version 2.4. Anything in the PEP is only for packages targeting 2.4. At least I think that was the intent...

>  reason why the metadata format is such a mess.

This lack of attention to detail is the reason why the metadata format is such a mess. :)

**Comment by dnicolodi** [comment] 2024-10-14 21:55
> Though is it?

I thought it was, but apparently is not: I haven't read the whole PEP again, but from your quote it seems that it is perfectly ok to produce metadata 2.4 with a `License` field as long as there is no `License-Expression` field with it. However, the PEP also says that tools reading the metadata (including package indexes, I believe) should treat `License-Expression` as higher priority than `License` not that they should fail validation if both are present. Fun!

**Comment by dnicolodi** [comment] 2024-10-14 21:57
> I took it to mean that the PEP only discusses metadata version 2.4. Anything in the PEP is only for packages targeting 2.4. At least I think that was the intent...

It would make sense for packages targeting metadata 2.4 to use a proper `pyproject.toml` structure, wouldn't it? I don't see why someone would require metadata 2.4 but keep their `pyproject.toml` using the fields defined for metadata 2.1. I would just emit an error if someone requires metadata 2.4 bus uses metadata 2.1 fileds in `pyproject.toml`.

I think that your implementation is the correct one.

**Comment by henryiii** [comment] 2024-10-14 22:22
That's assuming that the METADATA 2.4 choice happens in the pyproject.toml, which it normally doesn't. 2.4 happens to be really perfect for auto-selecting the metadata_version, since it changed the pyproject.toml fields. But normally a backend picks this; for example, hatching simply sets METADATA 2.3. So you have to describe what to do when 2.4 is set and the old pyproject.toml values are used. This will also come up with METADATA 2.5+.

**Comment by henryiii** [comment] 2024-10-14 22:27
On the actual topic of this issue (sorry for hijacking it!), on Discord several people thought the license file should be preserved exactly if specified, including the trailing newline.

**Comment by dnicolodi** [comment] 2024-10-14 22:30
> That's assuming that the METADATA 2.4 choice happens in the pyproject.toml

Independently that where it happens, I think it should not depend on the version of the build backend (or on the version of the packages on which the build backed depends). That would mean that the build backend cannot be updated to a version supporting the new metadata version untill the package index is not updated to accept it.

**Comment by dnicolodi** [comment] 2024-10-14 22:33
> On the actual topic of this issue (sorry for hijacking it!), on Discord several people thought the license file should be preserved exactly if specified, including the trailing newline.

I don't mind either way, but I don't see how white space is at the same important (we need to preserve trailing newlines) and not important (leading white space is not removed from continuation lines when metadata is read).

**Comment by henryiii** [comment] 2024-10-15 01:57
I may have overstated the support, two comments, one in favor of keeping the newline, and one in favor of always adding one. :)

The JSON interface returns the exact original contents.

The Message interface returns something with fixed whitespace after every newline except the first one. You can use `inspect.cleandoc` to get the oringinal file back... Except it strips all trailing newlines! 🤦. In theory, though, you could figure out and restore the original file exactly, assuming you have a email.message implementation like the one in Python that keeps these. It's also a valid implementation to just join them all, which of course makes this all one line anyway. But then again, this doesn't follow any standard really anyway, with unicode, etc...

I'll check and see what setuptools and hatching do, and if either of those strip, it's probably fine too.

I have no idea why someone thought `license.file` should fill in this metadata field which has stated (since [METADATA 1.1](https://peps.python.org/pep-0314/)!):

> Text indicating the license covering the package where the license is not a selection from the “License” Trove classifiers.

**Comment by henryiii** [comment] 2024-10-15 04:25
This exactly matches setuptools:

```bash
uvx cookiecutter gh:scientific-python/cookie
# Answer questions
cd package
uv build --sdist
```

```
Metadata-Version: 2.1
Name: package
Version: 0.1.0
Summary: A great package.
Author-email: My Name <me@email.com>
License: BSD 3-Clause License
        
        Copyright (c) 2024, My Name.
        All rights reserved.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:
        
        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.
        
        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
          and/or other materials provided with the distribution.
        
        * Neither the name of the vector package developers nor the names of its
          contributors may be used to endorse or promote products derived from
          this software without specific prior written permission.
        
        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
        AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
        FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
        SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
        CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
        OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
        
Project-URL: Homepage, https://github.com/org/package
...
```

But Hatchling strips it:

```
Metadata-Version: 2.3
Name: package
Version: 0.1.0
Summary: A great package.
Project-URL: Homepage, https://github.com/org/package
Project-URL: Bug Tracker, https://github.com/org/package/issues
Project-URL: Discussions, https://github.com/org/package/discussions
Project-URL: Changelog, https://github.com/org/package/releases
Author-email: My Name <me@email.com>
License: BSD 3-Clause License
        
        Copyright (c) 2024, My Name.
        All rights reserved.
        
        Redistribution and use in source and binary forms, with or without
        modification, are permitted provided that the following conditions are met:
        
        * Redistributions of source code must retain the above copyright notice, this
          list of conditions and the following disclaimer.
        
        * Redistributions in binary form must reproduce the above copyright notice,
          this list of conditions and the following disclaimer in the documentation
          and/or other materials provided with the distribution.
        
        * Neither the name of the vector package developers nor the names of its
          contributors may be used to endorse or promote products derived from
          this software without specific prior written permission.
        
        THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
        AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
        IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
        DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
        FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
        DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
        SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
        CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
        OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
        OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
License-File: LICENSE
Classifier: Development Status :: 1 - Planning
```

(Hatchling also uses License-File and `/licenses`, and has supported these features for many months from an early version of the PEP.)

**Comment by henryiii** [comment] 2024-10-15 04:26
FWIW, I like the way the setuptools one looks a bit better with the extra line at the end.

**Comment by dnicolodi** [comment] 2024-10-15 10:44
> FWIW, I like the way the setuptools one looks a bit better with the extra line at the end.

If we are in "taste for how the output looks like" territory 😄 I don't understand the choice to prefix the lines following the first with a number of spacer equal to the key length plus one, instead than accounting for the column and the whit space and add two spaces. Namely, I find that
```
License: Foo
         Bar
         Baz
```
is much more pleasant to look at than
```
License: Foo
        Bar
        Baz
```
It really looks like and off-by-one error to me. But it may just be me. 😄

**Comment by henryiii** [comment] 2024-10-15 14:42
This matches setuptools, I was just trying not to introduce more ways to do things. I agree that an extra space looks better. :) To be fair, I'd also be fine with two spaces, though, if we aren't avoiding adding a new style. @zanieb, did you (or someone else from Astral) say you were working on metadata and you followed the conventions here? Happy to take input if you have any. :)

**Comment by henryiii** [comment] 2024-10-22 04:40
I like that the current version exactly reproduces in the `json` versions, so let's go with the current version unless someone feels strongly otherwise.

**Closed** 2024-10-23 03:35 UTC
